pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                echo '📥 Cloning code from GitHub For Frontend...'
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                echo '🐳 Building Docker image for frontend...'
               sh 'docker build -t edprowise-frontend -f edprowise/Dockerfile edprowise'
            }
        }

        stage('Run Docker Container') {
            steps {
                echo '🚀 Running Docker container for frontend...'

                // Stop and remove old container if exists
                sh '''
                if [ $(docker ps -aq -f name=edprowise-frontend-container) ]; then
                  docker stop edprowise-frontend-container || true
                  docker rm edprowise-frontend-container || true
                fi

                docker run -d \
                  --name edprowise-frontend-container \
                  -p 80:80\
                  edprowise-frontend
                '''
            }
        }
    }

    post {
        success {
            echo '✅ Deployment completed successfully For Frontend!'
        }
        failure {
            echo '❌ Build or deployment failed For Frontend!'
        }
    }
}
